kind: Simple
apiVersion: k3d.io/v1alpha4
metadata: 
  name: airflow-cluster
servers: 1
agents: 3
volumes:
  - volume: $HOME/projects/nytaxi/data:/tmp/data
    nodeFilters:
      - server:0
      - agent:*
options:
  k3s:
    nodeLabels:
      - label: airflow 
        nodeFilters:
          - agent:*
