apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/airflow-config: 0bd9ea832e44a40479a8204d74ba357bba823b3bb921b91f2abca91f3cbb0478
    checksum/extra-configmaps: 2e44e493035e2f6a255d08f8104087ff10d30aef6f63176f1b18f75f73295598
    checksum/extra-secrets: bb91ef06ddc31c0c5a29973832163d8b0b597812a793ef911d33b622bc9d1655
    checksum/kerberos-keytab: 18b80c0921e5c0af1e63eca1c3ce3fbc388d006bd2db5a7ab512dc8a563b6443
    checksum/metadata-secret: dcbb26b06a9d686bf5fedceff6d4024447053fded58a37271cdfef14f8c8c800
    checksum/pgbouncer-config-secret: da52bd1edfe820f0ddfacdebb20a4cc6407d296ee45bcb500a6407e2261a5ba2
    checksum/result-backend-secret: 81fd0bc85dc6b240d98a984a508d94f010a012348f2ce63d2a262b0cbc6e0356
    checksum/webserver-secret-key: e27c90c91521d08263dcfc2af057c590da4b3b4c2b8a01691fbf1dc9dc58cd95
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  creationTimestamp: "2022-05-15T02:17:59Z"
  generateName: airflow-worker-
  labels:
    component: worker
    controller-revision-hash: airflow-worker-86ddc98854
    release: airflow
    statefulset.kubernetes.io/pod-name: airflow-worker-0
    tier: airflow
  name: airflow-worker-0
  namespace: airflow
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: airflow-worker
    uid: 212a24ea-ccd4-48f4-8072-f0cf330898e0
  resourceVersion: "16711"
  uid: e7b6fdc4-92d2-4abe-bf4a-40eb8f9b6249
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              component: worker
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - bash
    - -c
    - |-
      exec \
      airflow celery worker
    env:
    - name: DUMB_INIT_SETSID
      value: "0"
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          key: fernet-key
          name: airflow-fernet-key
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-metadata
    - name: AIRFLOW_CONN_AIRFLOW_DB
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-metadata
    - name: AIRFLOW__WEBSERVER__SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: webserver-secret-key
          name: airflow-webserver-secret-key
    - name: AIRFLOW__CELERY__CELERY_RESULT_BACKEND
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-result-backend
    - name: AIRFLOW__CELERY__RESULT_BACKEND
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-result-backend
    - name: AIRFLOW__CELERY__BROKER_URL
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-broker-url
    image: apache/airflow:2.2.4
    imagePullPolicy: IfNotPresent
    name: worker
    ports:
    - containerPort: 8793
      name: worker-logs
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 51Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/airflow/logs
      name: logs
    - mountPath: /opt/airflow/airflow.cfg
      name: config
      readOnly: true
      subPath: airflow.cfg
    - mountPath: /opt/airflow/config/airflow_local_settings.py
      name: config
      readOnly: true
      subPath: airflow_local_settings.py
    - mountPath: /opt/airflow/dags
      name: dags
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jhkzn
      readOnly: true
  - env:
    - name: GIT_SSH_KEY_FILE
      value: /etc/git-secret/ssh
    - name: GIT_SYNC_SSH
      value: "true"
    - name: GIT_KNOWN_HOSTS
      value: "false"
    - name: GIT_SYNC_REV
      value: HEAD
    - name: GIT_SYNC_BRANCH
      value: main
    - name: GIT_SYNC_REPO
      value: ssh://git@github.com/rafzul/airflow_dags.git
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_ROOT
      value: /git
    - name: GIT_SYNC_DEST
      value: repo
    - name: GIT_SYNC_ADD_USER
      value: "true"
    - name: GIT_SYNC_WAIT
      value: "60"
    - name: GIT_SYNC_MAX_SYNC_FAILURES
      value: "2"
    image: k8s.gcr.io/git-sync/git-sync:v3.4.0
    imagePullPolicy: IfNotPresent
    name: git-sync
    resources: {}
    securityContext:
      runAsUser: 65533
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /git
      name: dags
    - mountPath: /etc/git-secret/ssh
      name: git-sync-ssh-key
      readOnly: true
      subPath: gitSshKey
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jhkzn
      readOnly: true
  - args:
    - bash
    - /clean-logs
    env:
    - name: AIRFLOW__LOG_RETENTION_DAYS
      value: "15"
    image: apache/airflow:2.2.4
    imagePullPolicy: IfNotPresent
    name: worker-log-groomer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/airflow/logs
      name: logs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jhkzn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: airflow-worker-0
  initContainers:
  - args:
    - airflow
    - db
    - check-migrations
    - --migration-wait-timeout=60
    env:
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          key: fernet-key
          name: airflow-fernet-key
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-metadata
    - name: AIRFLOW_CONN_AIRFLOW_DB
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-metadata
    - name: AIRFLOW__WEBSERVER__SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: webserver-secret-key
          name: airflow-webserver-secret-key
    - name: AIRFLOW__CELERY__CELERY_RESULT_BACKEND
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-result-backend
    - name: AIRFLOW__CELERY__RESULT_BACKEND
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-airflow-result-backend
    - name: AIRFLOW__CELERY__BROKER_URL
      valueFrom:
        secretKeyRef:
          key: connection
          name: airflow-broker-url
    image: apache/airflow:2.2.4
    imagePullPolicy: IfNotPresent
    name: wait-for-airflow-migrations
    resources:
      limits:
        cpu: 100m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 51Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/airflow/airflow.cfg
      name: config
      readOnly: true
      subPath: airflow.cfg
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jhkzn
      readOnly: true
  - env:
    - name: GIT_SSH_KEY_FILE
      value: /etc/git-secret/ssh
    - name: GIT_SYNC_SSH
      value: "true"
    - name: GIT_KNOWN_HOSTS
      value: "false"
    - name: GIT_SYNC_REV
      value: HEAD
    - name: GIT_SYNC_BRANCH
      value: main
    - name: GIT_SYNC_REPO
      value: ssh://git@github.com/rafzul/airflow_dags.git
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_ROOT
      value: /git
    - name: GIT_SYNC_DEST
      value: repo
    - name: GIT_SYNC_ADD_USER
      value: "true"
    - name: GIT_SYNC_WAIT
      value: "60"
    - name: GIT_SYNC_MAX_SYNC_FAILURES
      value: "2"
    - name: GIT_SYNC_ONE_TIME
      value: "true"
    image: k8s.gcr.io/git-sync/git-sync:v3.4.0
    imagePullPolicy: IfNotPresent
    name: git-sync-init
    resources: {}
    securityContext:
      runAsUser: 65533
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /git
      name: dags
    - mountPath: /etc/git-secret/ssh
      name: git-sync-ssh-key
      readOnly: true
      subPath: gitSshKey
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jhkzn
      readOnly: true
  nodeName: k3d-airflow-cluster-agent-1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
    runAsUser: 50000
  serviceAccount: airflow-worker
  serviceAccountName: airflow-worker
  subdomain: airflow-worker
  terminationGracePeriodSeconds: 600
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: logs
    persistentVolumeClaim:
      claimName: logs-airflow-worker-0
  - configMap:
      defaultMode: 420
      name: airflow-airflow-config
    name: config
  - emptyDir: {}
    name: dags
  - name: git-sync-ssh-key
    secret:
      defaultMode: 288
      secretName: airflow-git-ssh-secret3
  - name: kube-api-access-jhkzn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-05-15T02:17:59Z"
    message: 'containers with incomplete status: [wait-for-airflow-migrations git-sync-init]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-05-15T02:17:59Z"
    message: 'containers with unready status: [worker git-sync worker-log-groomer]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-05-15T02:17:59Z"
    message: 'containers with unready status: [worker git-sync worker-log-groomer]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-05-15T02:17:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: k8s.gcr.io/git-sync/git-sync:v3.4.0
    imageID: ""
    lastState: {}
    name: git-sync
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  - image: apache/airflow:2.2.4
    imageID: ""
    lastState: {}
    name: worker
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  - image: apache/airflow:2.2.4
    imageID: ""
    lastState: {}
    name: worker-log-groomer
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  hostIP: 172.24.0.5
  initContainerStatuses:
  - image: apache/airflow:2.2.4
    imageID: ""
    lastState: {}
    name: wait-for-airflow-migrations
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: PodInitializing
  - image: k8s.gcr.io/git-sync/git-sync:v3.4.0
    imageID: ""
    lastState: {}
    name: git-sync-init
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: PodInitializing
  phase: Pending
  qosClass: Burstable
  startTime: "2022-05-15T02:17:59Z"
