kind: Simple
apiVersion: k3d.io/v1alpha4
metadata: 
  name: airflow-cluster
servers: 1
agents: 3
volumes:
  - volume: $HOME/projects/nytaxi/data:/var/lib/rancher/k3s/storage@all
    nodeFilters:
        - server:0
        - agent:*
options:
  k3s:
    nodeLabels:
      - label: airflow-worker 
        nodeFilters:
          - agent:*
