kind: Simple
apiVersion: k3d.io/v1alpha4
metadata: 
  name: airflow-cluster
servers: 1
agents: 3
volumes:
  - volume: /media/rafzul/terminal_dogma/nytaxidata:/storage
    nodeFilters:
        - server:0
        - agent:*
options:
  k3s:
    nodeLabels:
      - label: airflow-worker 
        nodeFilters:
          - agent:*
