kind: Simple
apiVersion: k3d.io/v1alpha4
metadata: 
  name: airflow-cluster
servers: 1
agents: 3
volumes:
  - volume: /winpop/k3s_storage:/var/lib/rancher/k3s/storage
    nodeFilters:
        - server:0
        - agent:*