apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-tmp
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
  
